### ISSUE TITLE
v3.0.1 keyboard shortcut does nothing

### ISSUE THREAD

**Issue by Endermanbugzjfc** [bibixx/tab-pinner#39]
v3.0.1 does not work on neither Mac nor Ubuntu so I need to downgrade to v2.3.0, which is the last functioning version. However, has a deprecated manifest version.
# Environment
**Chrome:** Version 104.0.5112.79 (Official Build) (64-bit)
**Mac:** 12.4
**Ubuntu:** 22.04

**Comment by bibixx** [comment]
@Endermanbugzjfc thanks for the feedback! I have forgotten to check it after migration (the key in manifest v3 for the keyboard action has changed as well)
The version 3.0.2 should be approved by Google in a Chrome Web Store in a few days.

Meanwhile you can try it out by loading the extension directly from the source code

1. Disable the current 3.0.1 version of the extension from the Chrome Web Store
2. Download the [tab-pinner.zip](https://github.com/bibixx/tab-pinner/releases/download/v3.0.2/tab-pinner.zip) from [Release v3.0.2](https://github.com/bibixx/tab-pinner/releases/tag/v3.0.2)
3. Unpack it into a convenient place
4. Go to chrome://extensions/
5. Turn on _Developer mode_ in the top right corner
6. Click _Load unpacked_
7. Select the unpacked folder

https://user-images.githubusercontent.com/14880213/184084444-5f55a51e-9480-4608-9727-c014d109658e.mp4
