### ISSUE TITLE
Accessing Chrome's extension keyboard shortcuts 

### ISSUE THREAD

**Issue by nicchristeller** [bibixx/tab-pinner#43]
Hi, thanks for the extension!

The only friction I had when setting things up was around the instructions of how to change the keyboard shortcuts:

**Issue**
The in-extension "How to change shortcut for pinning/unpinning/closing tab?" instructions directed me to the bottom of the `chrome://extensions` page. For me, there is no link to the shortcuts page here [Version 111.0.5563.64 (Official Build) (x86_64)].

**Solution**
I couldn't find a way to access the page from the UI, but navigating directly to `chrome://extensions/shortcuts` works, so it might be worth sending people there directly.

**Comment by bibixx** [comment]
Hi. Thanks for the feedback!
Those directions were written a long time ago, for an older version of Chrome, so that's probably why it wasn't there 😄 
I'll try to update it soon and maybe add a small video tutorial on how to do it.

**Comment by bibixx** [comment]
Please note, that the Store release was only just submitted to Google and now needs to be approved before it is available publically
